services:
  zone4:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - plant-network
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:cached
      - ~/.config:/home/${USERNAME}/.config:cached
      - ~/.wakatime.cfg:/home/${USERNAME}/.wakatime.cfg:cached
      - ~/.cache:/home/${USERNAME}/.cache:cached
      - ~/.netrc:/home/${USERNAME}/.netrc:cached
      - /data/plant-data-collection:/data/plant-data-collection:cached
    restart: unless-stopped
    command: uv run python src/main.py -e experiments/incubation/Incubator4.json -i 0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  zone5:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - plant-network
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:cached
      - ~/.config:/home/${USERNAME}/.config:cached
      - ~/.wakatime.cfg:/home/${USERNAME}/.wakatime.cfg:cached
      - ~/.cache:/home/${USERNAME}/.cache:cached
      - ~/.netrc:/home/${USERNAME}/.netrc:cached
      - /data/plant-data-collection:/data/plant-data-collection:cached
    restart: unless-stopped
    command: uv run python src/main_real.py -e experiments/online/E13/P0/Spreadsheet5.json -i 17 --deploy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  zone6:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - plant-network
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:cached
      - ~/.config:/home/${USERNAME}/.config:cached
      - ~/.wakatime.cfg:/home/${USERNAME}/.wakatime.cfg:cached
      - ~/.cache:/home/${USERNAME}/.cache:cached
      - ~/.netrc:/home/${USERNAME}/.netrc:cached
      - /data/plant-data-collection:/data/plant-data-collection:cached
    restart: unless-stopped
    command: uv run python src/main_real.py -e experiments/online/E13/P0/Spreadsheet6.json -i 18 --deploy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  zone7:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - plant-network
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:cached
      - ~/.config:/home/${USERNAME}/.config:cached
      - ~/.wakatime.cfg:/home/${USERNAME}/.wakatime.cfg:cached
      - ~/.cache:/home/${USERNAME}/.cache:cached
      - ~/.netrc:/home/${USERNAME}/.netrc:cached
      - /data/plant-data-collection:/data/plant-data-collection:cached
    restart: unless-stopped
    command: uv run python src/main_real.py -e experiments/online/E13/P0/Dirichlet7.json -i 19 --deploy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  zone8:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - plant-network
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:cached
      - ~/.config:/home/${USERNAME}/.config:cached
      - ~/.wakatime.cfg:/home/${USERNAME}/.wakatime.cfg:cached
      - ~/.cache:/home/${USERNAME}/.cache:cached
      - ~/.netrc:/home/${USERNAME}/.netrc:cached
      - /data/plant-data-collection:/data/plant-data-collection:cached
    restart: unless-stopped
    command: uv run python src/main_real.py -e experiments/online/E13/P0/Spreadsheet8.json -i 20 --deploy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  zone9:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - plant-network
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:cached
      - ~/.config:/home/${USERNAME}/.config:cached
      - ~/.wakatime.cfg:/home/${USERNAME}/.wakatime.cfg:cached
      - ~/.cache:/home/${USERNAME}/.cache:cached
      - ~/.netrc:/home/${USERNAME}/.netrc:cached
      - /data/plant-data-collection:/data/plant-data-collection:cached
    restart: unless-stopped
    command: uv run python src/main_real.py -e experiments/online/E13/P0/Spreadsheet9.json -i 21 --deploy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  zone10:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - plant-network
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:cached
      - ~/.config:/home/${USERNAME}/.config:cached
      - ~/.wakatime.cfg:/home/${USERNAME}/.wakatime.cfg:cached
      - ~/.cache:/home/${USERNAME}/.cache:cached
      - ~/.netrc:/home/${USERNAME}/.netrc:cached
      - /data/plant-data-collection:/data/plant-data-collection:cached
    restart: unless-stopped
    command: uv run python src/main_real.py -e experiments/online/E13/P0/Spreadsheet10.json -i 22 --deploy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  zone11:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - plant-network
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:cached
      - ~/.config:/home/${USERNAME}/.config:cached
      - ~/.wakatime.cfg:/home/${USERNAME}/.wakatime.cfg:cached
      - ~/.cache:/home/${USERNAME}/.cache:cached
      - ~/.netrc:/home/${USERNAME}/.netrc:cached
      - /data/plant-data-collection:/data/plant-data-collection:cached
    restart: unless-stopped
    command: uv run python src/main_real.py -e experiments/online/E13/P0/Spreadsheet11.json -i 23 --deploy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  zone12:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        USER_UID: ${HOST_UID}
        USER_GID: ${HOST_GID}
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - plant-network
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - .:/app:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/home/${USERNAME}/.ssh:cached
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:cached
      - ~/.config:/home/${USERNAME}/.config:cached
      - ~/.wakatime.cfg:/home/${USERNAME}/.wakatime.cfg:cached
      - ~/.cache:/home/${USERNAME}/.cache:cached
      - ~/.netrc:/home/${USERNAME}/.netrc:cached
      - /data/plant-data-collection:/data/plant-data-collection:cached
    restart: unless-stopped
    command: uv run python src/main_real.py -e experiments/online/E13/P0/Spreadsheet12.json -i 24 --deploy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

networks:
  plant-network:
    name: plant-network
    external: true