version: "2"

services:
  app:
    image: ghcr.io/steventango/plant-rl/camera2:dockerize-apis
    ports:
      - 8080:80
    privileged: true
    restart: unless-stopped
    volumes:
      - /run/udev:/run/udev:ro
      - .:/app
