name: Test Camera API

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python-test-camera-api.yml'
      - 'api/camera/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python-test-camera-api.yml'
      - 'api/camera/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.11
    - run: uv sync --prerelease=allow --requirements api/camera/requirements-test.txt
    - name: Test with pytest
      run: |
        uv run pytest api/camera/tests
