name: Test Status API

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python-test-status-api.yml'
      - 'api/status/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python-test-status-api.yml'
      - 'api/status/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.11
    - run: uv sync --prerelease=allow --requirements api/status/requirements.txt
    - name: Test with pytest
      run: |
        uv run pytest api/status/tests
