name: Test Lightbar API

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python-test-lightbar-api.yml'
      - 'api/lightbar/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python-test-lightbar-api.yml'
      - 'api/lightbar/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.11
    - run: |
        uv venv
        uv pip install -r api/lightbar/requirements.txt
    - name: Test with pytest
      run: uv run pytest api/lightbar/tests
