name: Test Lightbar API

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python-test-lightbar-api.yml'
      - 'api/lightbar/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/python-test-lightbar-api.yml'
      - 'api/lightbar/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.11
    - run: uv sync --prerelease=allow --requirements api/lightbar/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 api/lightbar --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        uv run flake8 api/lightbar --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        uv run pytest api/lightbar/tests
